version = 1

[*]
batch-size = 1024
jinja = on

; # Gemma 4 12B (256K Context, QAT, MTP)
[gemma-4-12b-qat-it]
; hf download unsloth/gemma-4-12B-it-qat-GGUF \
;     --local-dir unsloth/gemma-4-12B-it-qat-GGUF \
;     --include "*mmproj-F16*" \
;     --include "mtp-*" \
;     --include "*UD-Q4_K_XL*"
;
;--alias "unsloth/gemma-4-12b-it-qat-GGUF" \
;--model unsloth/gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf \
;--mmproj unsloth/gemma-4-12B-it-qat-GGUF/mmproj-F16.gguf \
;--model-draft unsloth/gemma-4-12B-it-qat-GGUF/mtp-gemma-4-12B-it.gguf \
;--temp 1.0 \
;--top-p 0.95 \
;--top-k 64  \
;--spec-type draft-mtp \
;--spec-draft-n-max 2
alias = unsloth/gemma-4-12b-it-qat-GGUF
model = unsloth/gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
mmproj = unsloth/gemma-4-12B-it-qat-GGUF/mmproj-F16.gguf
model-draft = unsloth/gemma-4-12B-it-qat-GGUF/mtp-gemma-4-12B-it.gguf
no-mmproj-offload = true
reasoning = true
flash-attn = true
parallel = 2
ctx-size = 262144
temp = 1.0 \
top-p = 0.95 \
top-k = 64  \
spec-type = draft-mtp \
spec-draft-n-max = 2
; load-on-startup = true

# Gemma 4 26B-A4B (256K Context, QAT, MTP)
[gemma-4-26b-a4b-qat-it]
; #     hf download unsloth/gemma-4-26B-A4B-it-qat-GGUF \
; #     --local-dir unsloth/gemma-4-26B-A4B-it-qat-GGUF \
; #     --include "*mmproj-BF16*" \
; #     --include "mtp-*" \
; #     --include "*UD-Q4_K_XL*"
; # 
;--alias "unsloth/gemma-4-26B-A4B-it-qat-GGUF" \
;--model unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf \
;--mmproj unsloth/gemma-4-26B-A4B-it-qat-GGUF/mmproj-BF16.gguf \
;--model-draft unsloth/gemma-4-26B-A4B-it-qat-GGUF/mtp-gemma-4-26B-A4B-it.gguf \
;--temp 1.0 \
;--top-p 0.95 \
;--top-k 64 \
;--spec-type draft-mtp \
;--spec-draft-n-max 2
; # Is this even needed?
; #     --chat-template-kwargs '{"enable_thinking":true}'

# Gemma 4 31B (256K Context, QAT, MTP)
[gemma-4-31b-qat-it]
; #     hf download unsloth/gemma-4-31B-it-qat-GGUF \
; #     --local-dir unsloth/gemma-4-31B-it-qat-GGUF \
; #     --include "*mmproj-BF16*" \
; #     --include "mtp-*" \
; #     --include "*UD-Q4_K_XL*"
; # 
;--alias "unsloth/gemma-4-31B-it-qat-GGUF" \
;--model unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf \
;--mmproj unsloth/gemma-4-31B-it-qat-GGUF/mmproj-BF16.gguf \
;--model-draft unsloth/gemma-4-31B-it-qat-GGUF/mtp-gemma-4-31B-it.gguf \
;--temp 1.0 \
;--top-p 0.95 \
;--top-k 64 \
;--spec-type draft-mtp \
;--spec-draft-n-max 2
alias = unsloth/gemma-4-31B-it-qat-GGUF
model = /Users/mhall/.cache/huggingface/hub/models--unsloth--gemma-4-31B-it-qat-GGUF/snapshots/365d657136993b4d7c40d868dd45ecb7a48e7ebf/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
mmproj = /Users/mhall/.cache/huggingface/hub/models--unsloth--gemma-4-31B-it-qat-GGUF/snapshots/365d657136993b4d7c40d868dd45ecb7a48e7ebf/mmproj-BF16.gguf
model-draft = /Users/mhall/.cache/huggingface/hub/models--unsloth--gemma-4-31B-it-qat-GGUF/snapshots/365d657136993b4d7c40d868dd45ecb7a48e7ebf/mtp-gemma-4-31B-it.gguf
no-mmproj-offload = true
reasoning = true
flash-attn = true
parallel = 2
ctx-size = 262144
temp = 1.0
top-p = 0.95
top-k = 64
; load-on-startup = true

; # Qwen 3.6 35B-A3B MTP
; # The only model that still requires a separate MTP GGUF is Qwen3.6.
; hf download unsloth/Qwen3.6-35B-A3B-MTP-GGUF \
;     --local-dir unsloth/Qwen3.6-35B-A3B-MTP-GGUF \
;     --include "*mmproj-F16*" \
;     --include "*UD-Q4_K_XL*"
;
; # General Use - For precise coding tasks, temperature=0.6
;     --model unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf \
;     --mmproj unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F16.gguf \
;     --temp 1.0 \
;     --top-p 0.95 \
;     --top-k 20 \
;     --min-p 0.00 \
;     --spec-type draft-mtp \
;     --spec-draft-n-max 2

; # Non-Thinking Mode
;     --model unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf \
;     --mmproj unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F16.gguf \
;     --temp 0.7 \
;     --top-p 0.8 \
;     --min-p 0.00 \
;     --top-k 20 \
;     --presence-penalty 1.5 \
;     --spec-type draft-mtp \
;     --spec-draft-n-max 2 \
;     --chat-template-kwargs '{"enable_thinking":false}'
[Qwen3.6-35B-A3B]
alias = unsloth/Qwen3.6-35B-A3B-MTP-GGUF
model = /Users/mhall/Workspaces/llama.cpp/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
mmproj = /Users/mhall/Workspaces/llama.cpp/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F16.gguf
no-mmproj-offload = true
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
ctx-size = 262144
parallel = 2
flash-attn = true
reasoning = true
spec-type = draft-mtp
spec-draft-n-max = 3
; load-on-startup = true

[Qwen3.6-35B-A3B-Coder]
alias = unsloth/Qwen3.6-35B-A3B-MTP-GGUF-Coder
model = /Users/mhall/Workspaces/llama.cpp/unsloth/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
mmproj = /Users/mhall/Workspaces/llama.cpp/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F16.gguf
no-mmproj-offload = true
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 1.5
ctx-size = 128000
parallel = 2
flash-attn = true
reasoning = false
spec-type = draft-mtp
spec-draft-n-max = 3
; load-on-startup = true

; # Qwen 3.6 27B MTP
;
; # The only model that still requires a separate MTP GGUF is Qwen3.6.
; hf download unsloth/Qwen3.6-27B-MTP-GGUF \
;     --local-dir unsloth/Qwen3.6-27B-MTP-GGUF \
;     --include "*mmproj-F16*" \
;     --include "*UD-Q4_K_XL*"
;
; # General Use - For precise coding tasks, temperature=0.6
;     --model unsloth/Qwen3.6-27B-MTP-GGUF/Qwen3.6-27B-UD-Q4_K_XL.gguf \
;     --mmproj unsloth/Qwen3.6-27B-MTP-GGUF/mmproj-F16.gguf \
;     --temp 1.0 \
;     --top-p 0.95 \
;     --top-k 20 \
;     --min-p 0.00 \
;     --spec-type draft-mtp \
;     --spec-draft-n-max 2

; # Non-Thinking Mode
;     --model unsloth/Qwen3.6-27B-MTP-GGUF/Qwen3.6-27B-UD-Q4_K_XL.gguf \
;     --mmproj unsloth/Qwen3.6-27B-MTP-GGUF/mmproj-F16.gguf \
;     --temp 0.7 \
;     --top-p 0.8 \
;     --min-p 0.00 \
;     --top-k 20 \
;     --presence-penalty 1.5 \
;     --spec-type draft-mtp \
;     --spec-draft-n-max 2 \
;     --chat-template-kwargs '{"enable_thinking":false}'
[Qwen3.6-27B-Coder]
alias = unsloth/Qwen3.6-27B-MTP-GGUF-Coder
model = /Users/mhall/.cache/huggingface/hub/models--unsloth--Qwen3.6-27B-MTP-GGUF/snapshots/5cb35eb3dcbf52dbce5f87dbc64df6aaffadcace/Qwen3.6-27B-UD-Q6_K_XL.gguf
mmproj = /Users/mhall/.cache/huggingface/hub/models--unsloth--Qwen3.6-27B-MTP-GGUF/snapshots/5cb35eb3dcbf52dbce5f87dbc64df6aaffadcace/mmproj-BF16.gguf
no-mmproj-offload = true
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 1.5
ctx-size = 176608
parallel = 2
flash-attn = true
reasoning = false
spec-type = draft-mtp
spec-draft-n-max = 3
; load-on-startup = true

# North Mini Code 1.0
[North-Mini-Code]
alias = unsloth/North-Mini-Code-1.0-GGUF
model = /Users/mhall/.cache/huggingface/hub/models--unsloth--North-Mini-Code-1.0-GGUF/snapshots/e306bb4bf0df610f5471d97a01de2b6e0b24d356/North-Mini-Code-1.0-UD-Q4_K_XL.gguf
temp = 1.0
top-p = 0.95
ctx-size = 256000
parallel = 2
flash-attn = true
reasoning = true
; load-on-startup = true
